build:
	tsc

download:
	node dist/main.js download

insert:
	node dist/main.js insert

drop:
	node dist/main.js drop

create:
	node dist/main.js create

debug:
	node dist/main.js debug

help:
	node dist/main.js --help
